# Generated by Django 3.1.4 on 2021-04-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Date_debut', models.DateField()),
                ('Date_fin', models.DateField()),
                ('Entite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pseudo', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100, null=True)),
                ('num', models.CharField(max_length=2)),
                ('Date_debut', models.DateField()),
                ('Date_fin', models.DateField()),
                ('Deadline', models.DateField()),
                ('id_chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Achat.chantier')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('id_chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Achat.chantier')),
            ],
        ),
        migrations.AddField(
            model_name='chantier',
            name='id_Gestionnaire',
            field=models.ManyToManyField(to='Achat.Responsable'),
        ),
    ]
