# Generated by Django 3.1.4 on 2021-04-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='état',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
