# Generated by Django 3.1.4 on 2021-04-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achat', '0002_phase_état'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='Date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
