# Generated by Django 3.1.4 on 2021-04-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Achat', '0003_auto_20210409_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='état',
            new_name='State',
        ),
    ]
