# Generated by Django 3.2 on 2021-06-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achat', '0006_alter_responsable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='id_Responsable',
            field=models.ManyToManyField(to='Achat.Responsable'),
        ),
    ]
