# Generated by Django 3.2 on 2021-06-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Achat', '0007_phase_id_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chantier',
            name='id_Responsable',
        ),
    ]
