# Generated by Django 3.2 on 2021-06-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achat', '0008_remove_chantier_id_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='Date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='Deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
